#!/usr/bin/env bash
set -euo pipefail

# create-release-pr.sh — Update version, prepend changelog, commit and push.
# If on a non-main branch with an existing PR, pushes to that branch.
# Otherwise creates a release branch and PR.
# Usage: create-release-pr.sh <new-version> <changelog-section-file>

REPO="Codagent-AI/agent-skills"
PLUGIN_JSON=".claude-plugin/plugin.json"
CODEX_PLUGIN_JSON=".codex-plugin/plugin.json"
CURSOR_PLUGIN_JSON=".cursor-plugin/plugin.json"
MARKETPLACE_JSON=".claude-plugin/marketplace.json"
CHANGELOG="CHANGELOG.md"

NEW_VERSION="${1:?Usage: create-release-pr.sh <new-version> <changelog-section-file>}"
CHANGELOG_FILE="${2:?Usage: create-release-pr.sh <new-version> <changelog-section-file>}"

if [[ ! "$NEW_VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
  echo "Error: invalid version '$NEW_VERSION' (expected X.Y.Z)" >&2
  exit 1
fi

if [ ! -f "$CHANGELOG_FILE" ]; then
  echo "Error: changelog section file not found: $CHANGELOG_FILE" >&2
  exit 1
fi

CURRENT_BRANCH=$(git branch --show-current)
TARGET_BRANCH="$CURRENT_BRANCH"
USE_EXISTING_PR=false

if [ "$CURRENT_BRANCH" != "main" ] \
  && gh pr view "$CURRENT_BRANCH" --repo "$REPO" --json url >/dev/null 2>&1; then
  USE_EXISTING_PR=true
else
  TARGET_BRANCH="release/v${NEW_VERSION}"
  git checkout -B "$TARGET_BRANCH"
fi

# --- Update plugin.json version ---
jq --arg v "$NEW_VERSION" '.version = $v' "$PLUGIN_JSON" > "${PLUGIN_JSON}.tmp" \
  && mv "${PLUGIN_JSON}.tmp" "$PLUGIN_JSON"

# --- Update codex plugin.json version ---
jq --arg v "$NEW_VERSION" '.version = $v' "$CODEX_PLUGIN_JSON" > "${CODEX_PLUGIN_JSON}.tmp" \
  && mv "${CODEX_PLUGIN_JSON}.tmp" "$CODEX_PLUGIN_JSON"

# --- Update cursor plugin.json version ---
jq --arg v "$NEW_VERSION" '.version = $v' "$CURSOR_PLUGIN_JSON" > "${CURSOR_PLUGIN_JSON}.tmp" \
  && mv "${CURSOR_PLUGIN_JSON}.tmp" "$CURSOR_PLUGIN_JSON"

# --- Update marketplace.json version ---
jq --arg v "$NEW_VERSION" '
  if any(.plugins[]; .name == "codagent") then
    .plugins |= map(if .name == "codagent" then .version = $v else . end)
  else
    error("Plugin \"codagent\" not found in marketplace.json")
  end
' "$MARKETPLACE_JSON" > "${MARKETPLACE_JSON}.tmp" \
  && mv "${MARKETPLACE_JSON}.tmp" "$MARKETPLACE_JSON"

# --- Prepend changelog section ---
if [ -f "$CHANGELOG" ]; then
  # Insert new section after the "# agent-skills" header line
  {
    head -1 "$CHANGELOG"
    echo ""
    cat "$CHANGELOG_FILE"
    # Remaining lines after the header
    tail -n +2 "$CHANGELOG"
  } > "${CHANGELOG}.tmp" && mv "${CHANGELOG}.tmp" "$CHANGELOG"
else
  {
    echo "# agent-skills"
    echo ""
    cat "$CHANGELOG_FILE"
  } > "$CHANGELOG"
fi

git add "$PLUGIN_JSON" "$CODEX_PLUGIN_JSON" "$CURSOR_PLUGIN_JSON" "$MARKETPLACE_JSON" "$CHANGELOG"
git commit -m "chore: release v${NEW_VERSION}"

if [ "$USE_EXISTING_PR" = true ]; then
  # --- Non-main branch with existing PR: push to that branch/PR ---
  git push

  # Print the existing PR URL
  gh pr view "$TARGET_BRANCH" --repo "$REPO" --json url --jq .url
else
  # --- Main or non-PR branch: create release branch and PR ---
  git push -u origin "$TARGET_BRANCH"

  if PR_URL=$(gh pr view "$TARGET_BRANCH" --repo "$REPO" --json url --jq .url 2>/dev/null); then
    echo "$PR_URL"
  else
    gh pr create --repo "$REPO" --base main --head "$TARGET_BRANCH" \
      --title "chore: release v${NEW_VERSION}" \
      --body "$(cat <<EOF
## Release v${NEW_VERSION}

This PR was generated by the \`/release\` skill.
EOF
)"
  fi
fi
